### ISSUE TITLE
In the case of HTML Paragraph, erroneous detection occurs.

### ISSUE THREAD

**Issue by kemsakurai** [textlint-rule/textlint-rule-no-start-duplicated-conjunction#3]
I applied the no-start-duplicated-conjunction rule to the HTML file.
The following Lint error occurred, but I think that this error is a false detection.

```console
  916:1011  error    Don't repeat "</p>" in 2 phrases    no-start-duplicated-conjunction
```

In the case of HTML, the data of the node of Paragraph is as follows.

```console
{ type: 'Paragraph',
  tagName: 'p',
  properties: {},
  children: 
   [ { type: 'Strong',
       tagName: 'strong',
       properties: {},
       children: [Array],
       loc: [Object],
       range: [Array],
       raw: '<strong>HTML と、Page クラスに Footer 部とする Container を追加する</strong>' },
     type: 'UNKNOWN' ],
  loc: 
   { start: { line: 1144, column: 36 },
     end: { line: 1144, column: 104 } },
  range: [ 46454, 46522 ],
  raw: '<p><strong>HTML と、Page クラスに Footer 部とする Container を追加する</strong></p>' }
```

In the case of Markdown, the data of the node is as follows.

```console
{ type: 'Paragraph',
  children: 
   [ { type: 'Code',
       value: 'o',
       loc: [Object],
       range: [Array],
       raw: '`o`' },
     { type: 'Str',
       value: ' をつけたルールを一律 グローバルインストールします。    ',
       loc: [Object],
       range: [Array],
       raw: ' をつけたルールを一律 グローバルインストールします。    ' } ],
  loc: 
   { start: { line: 117, column: 0 },
     end: { line: 117, column: 34 } },
  range: [ 5761, 5795 ],
  raw: '`o` をつけたルールを一律 グローバルインストールします。    ' }
```

I thought false detection occurred because HTML tags included in the `raw` property of the Paragraph node generated from HTML.
I attempted to fix it. but I could not decide whether to remove HTML tags on the rule side or whether HTML parser should remove the HTML tag of `raw` property.

**Comment by azu** [comment]
> HTML tags included in the raw property of the Paragraph node generated from HTML.

`Paragraph` node's `raw` includes raw HTML String is valid.
`String` node's `raw`  includes `<strong>` HML string is valid.

For example, `**text**` in markdown, the node's `raw` include `**` string.

![image](https://user-images.githubusercontent.com/19714/33018053-2a4a033e-ce38-11e7-9a75-80d258da65c2.png)
> https://textlint.github.io/astexplorer/


Is HTML text that is tested `<p><strong>HTML と、Page クラスに Footer 部とする Container を追加する</strong></p>` ?

----

Notes: maybe, this rule can use [textlint-util-to-string](https://github.com/textlint/textlint-util-to-string "textlint-util-to-string").

```
const StringSource = require("textlint-util-to-string");
const source = new StringSource(node);
const text = source.toString();
// This `text` should be plain text.
```

insteadof 

```
const text = getSource(node);
```

Or this rule collect `Str` nodes and concat it.

**Comment by kemsakurai** [comment]
Thank you for answering.
I understood the possible value of raw.

> Is HTML text that is tested <p> <strong> Add HTML and Container to be the Footer part to the Page class </ strong> </ p>?

This value was as an example.
It is not a Node in which the problem actually occurred.
sorry.

I will try using  [textlint-util-to-string](https://github.com/textlint/textlint-util-to-string) to see if it works well.
